// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StajApi.Data;

#nullable disable

namespace StajApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730221710_AddPasswordHashAndUserType")]
    partial class AddPasswordHashAndUserType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StajApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "fatih.ulus@pointr.tech",
                            Name = "Fatih",
                            PasswordHash = "AQAAAAIAAYagAAAAEH4nbj6VFxAKSxyW7OdvUWLM/DbLFYNNxKmqZbDxISIfYSonPTZ+TdQUj8DAU8VVJw==",
                            UserType = "User"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "rustem.akkaya@pointr.tech",
                            Name = "Rüstem",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3SSIEZyc2COS0QT5qAs7pmAIQY+vBMcD35m5nlqGyZZ8drc66hNOoVX3uIv6BAUA==",
                            UserType = "User"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "kaan.kesen@pointr.tech",
                            Name = "Kaan",
                            PasswordHash = "AQAAAAIAAYagAAAAEFzMCYbtMyaU6/phz5IYJm7zfBykYk/pGnV6Zkai/kA7nIh9bCp8TLJs8v694AtN0w==",
                            UserType = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
